### ISSUE TITLE
option defaults can no longer have length zero

### ISSUE THREAD

**Issue by tyner** [trevorld/optparse#14]
In version 1.0.2, option defaults were allowed to have length zero. But it seems in the latest version, this is not allowed, failing with:

    Error in if (is.na(default)) { : argument is of length zero
    Calls: parse_args -> print_help -> cat -> sub -> .as_string                
    5: parse_args(opt.parser, positional_arguments = TRUE)                     
    4: print_help(object)                                                      
    3: cat(sub("%default", .as_string(option@default), option@help))           
    2: sub("%default", .as_string(option@default), option@help)                
    1: .as_string(option@default)

any thoughts on whether support for option defaults having length zero could/should be restored?

Thanks
Ben

**Comment by trevorld** [comment]
Should be fixed in the development version now and a zero-length default argument now explicitly tested in the unit tests.

**Comment by tyner** [comment]
Thanks!
