### ISSUE TITLE
Apparent cut-and-paste error in documentation

### ISSUE THREAD

**Issue by jjramsey** [trevorld/optparse#23]
The documentation for the "default" argument of "make_option" reads "The default value optparse should use if it does not find the option on the command line. *Default is derived from the long flag in opt_str.*" [emphasis added]. This doesn't seem to make much sense, since there doesn't appear to be any documentation on how to derive the default from the long flag. Rather, the emphasized part looks like a cut-and-paste from the documention of the "dest" argument, which reads "A character string that specifies what field in the list returned by parse_args should optparse store option values. *Default is derived from the long flag in opt_str.*"

**Comment by trevorld** [comment]
Thanks for the report!  Should be fixed in the developmental version now.
