### ISSUE TITLE
"-g" argument raises warning

### ISSUE THREAD

**Issue by hmontenegro** [trevorld/optparse#24]
When using `-g` as argument and calling the script on the command-line, the value of `-g` is used both to set the GUI and later inside the script. A small example:

```
#!/usr/bin/env Rscript
suppressPackageStartupMessages( library(optparse) )
option_list = list(
  make_option( c("-t", "--trait"), type="double", default=0.99, 
               help="trait frequency" ),
  make_option( c("-g", "--generations"), type="integer", default=1000,
               help="number of generations to run" ) ); 

opt_parser = OptionParser(option_list=option_list);
opt = parse_args(opt_parser);
write(  opt$trait, stdout( ) )
write( opt$generations, stdout( ) )
```

Save as "script.R" and run:

```
./script.R -t 0.4 -g 5
WARNING: unknown gui '5', using X11

0.4
5
```

But:

```
./script -t 0.4 -g X11
Warning message:
In storage.mode(peek.optstring) = spec[current.flag, col.mode] :
  NAs introduced by coercion
0.4
NA
```

`-g` is used first to set the GUI, then to set opt$generations. If using `--generations`, no warnings occur.

**Comment by trevorld** [comment]
Looks like a bug in ``Rscript`` (which isn't even supposed to have an `-g` option to set unlike the ``R`` command and even if it did isn't supposed to parse arguments placed after the filename).  I'll plan on submitting a bug report to the R Team in the next few days.  Kind of a pain since I'll need to upgrade to the development version of R first to make sure it hasn't been fixed before submitting the report.

**Comment by trevorld** [comment]
R's bug reporting system doesn't allow new bug reports (unless you are a pre-approved poster) so I've sent a bug report e-mail to the R-devel mailing list.  It is awaiting moderator approval.

**Comment by trevorld** [comment]
On the R-devel mailing list now:

https://stat.ethz.ch/pipermail/r-devel/2017-October/075026.html

**Comment by hmontenegro** [comment]
Thanks for the very quick reply and for following up and filling the bug report. And thanks for optparse, it is really nifty.

**Comment by trevorld** [comment]
This bug should have been fixed in the development version of R.

https://stat.ethz.ch/pipermail/r-devel/2017-November/075122.html
