### ISSUE TITLE
Passing zero length strings

### ISSUE THREAD

**Issue by MrFlick** [trevorld/optparse#25]
Is it correct that you can't pass in a zero length strings as an argument? For example

    Rscript sample.R --test=""

where sample.R contains

```
require(optparse)
get_options <- function() {
    option_list <- list(
      make_option("--test", type="character", default="apple")
    )
    parser <- OptionParser(usage="%prog [options]", option_list=option_list)
    args <- parse_args(parser, positional_arguments = 0)
    opt <- args$options
    opt
}


print(commandArgs())
get_options()
```

I get the response

```
Loading required package: optparse
[1] "/usr/lib/R/bin/exec/R" "--slave"               "--no-restore"
[4] "--file=sample.R"          "--args"                "--test="
Error in getopt(spec = spec, opt = args) : long flag "test=" is invalid
Calls: get_options -> parse_args -> getopt
Execution halted
```

So the empty quotes seem to basically disappear when R parses the arguments first.

I wasn't sure if this was the desired behavior.

Tested with `R version 3.4.3 (2017-11-30); Platform: x86_64-pc-linux-gnu (64-bit)`

**Comment by trevorld** [comment]
Thanks for the bug report!  

Note that although I don't necessarily recommend dropping the ``=`` with long flag options technically you can currently pass a zero length string if you do so (either with a short flag option or long flag option):

````
bash$ Rscript tmp/test.R --test foo
Loading required package: optparse
[1] "/usr/lib/R/bin/exec/R" "--slave"               "--no-restore"         
[4] "--file=tmp/test.R"     "--args"                "--test"               
[7] "foo"                  
$test
[1] "foo"

$help
[1] FALSE
````

Looks like python's ``optparse`` module which inspired this package allows passing empty string so this should be considered a previously unknown and unreported bug.  

I need to check if C's getopt module (which inspired the ``getopt`` package which does most of ``optparse``'s actual parsing) allows passing empty strings in which case I should probably directly patch that package such that no observed argument for a character option should be interpreted as an empty string.

**Comment by trevorld** [comment]
Should be fixed now if you upgrade to the development version of ``getopt``.  Reminder to oneself that after submitting ``getopt`` to CRAN to increment minimum getopt requirement in DESCRIPTION.
