### ISSUE TITLE
Convert hyphens to underscores.

### ISSUE THREAD

**Issue by audy** [trevorld/optparse#9]
Just a suggestion.

Python's `argparse` automatically converts hyphens to underscores.

I think this behavior would suit optparse because column names containing hyphens can't be subsetted the same way as underscores:

```S
library(optparse)

option_list <-  c(make_option('--some-option'))

parser <- OptionParser(option_list = option_list)

options <- parse_args(parser)

print(options$some-option) # crashes

print(options$[,'some-option']) # ugly

print(options$some_option) # nice
```

What do you think? I could write the code and send you a PR if you agree.

**Comment by mavam** [comment]
Too bad this won't get fixed, I'll go with the workaround then: `print(options$`some-option`)`

**Comment by trevorld** [comment]
In the developmental version of optparse I've added an option `convert_hyphens_to_underscores` to `parse_args` which does what you want.  I've also added the convenience warpper `parse_args2` which wraps `parse_args` setting `convert_hyphens_to_underscores` to `TRUE` and `positional_arguments` to `TRUE`.
